// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_500 from "./routes/_500.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $api_kv_id_path_ from "./routes/api/kv/[id]/[...path].ts";
import * as $api_kv_id_index from "./routes/api/kv/[id]/index.ts";
import * as $api_local_index from "./routes/api/local/index.ts";
import * as $api_remote_check from "./routes/api/remote/check.ts";
import * as $api_remote_index from "./routes/api/remote/index.ts";
import * as $docs_index from "./routes/docs/index.tsx";
import * as $index from "./routes/index.tsx";
import * as $local_id_ from "./routes/local/[id].tsx";
import * as $local_index from "./routes/local/index.tsx";
import * as $login from "./routes/login.tsx";
import * as $logout from "./routes/logout.tsx";
import * as $orgs_id_ from "./routes/orgs/[id].tsx";
import * as $orgs_index from "./routes/orgs/index.tsx";
import * as $projects_name_index from "./routes/projects/[name]/index.tsx";
import * as $projects_name_kv_branch_ from "./routes/projects/[name]/kv/[branch].tsx";
import * as $remote_id_ from "./routes/remote/[id].tsx";
import * as $remote_index from "./routes/remote/index.tsx";
import * as $user from "./routes/user.ts";
import * as $KvExplorer from "./islands/KvExplorer.tsx";
import * as $LocalKvList from "./islands/LocalKvList.tsx";
import * as $RemoteControls from "./islands/RemoteControls.tsx";
import * as $RemoteKvList from "./islands/RemoteKvList.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_500.tsx": $_500,
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.ts": $_middleware,
    "./routes/api/kv/[id]/[...path].ts": $api_kv_id_path_,
    "./routes/api/kv/[id]/index.ts": $api_kv_id_index,
    "./routes/api/local/index.ts": $api_local_index,
    "./routes/api/remote/check.ts": $api_remote_check,
    "./routes/api/remote/index.ts": $api_remote_index,
    "./routes/docs/index.tsx": $docs_index,
    "./routes/index.tsx": $index,
    "./routes/local/[id].tsx": $local_id_,
    "./routes/local/index.tsx": $local_index,
    "./routes/login.tsx": $login,
    "./routes/logout.tsx": $logout,
    "./routes/orgs/[id].tsx": $orgs_id_,
    "./routes/orgs/index.tsx": $orgs_index,
    "./routes/projects/[name]/index.tsx": $projects_name_index,
    "./routes/projects/[name]/kv/[branch].tsx": $projects_name_kv_branch_,
    "./routes/remote/[id].tsx": $remote_id_,
    "./routes/remote/index.tsx": $remote_index,
    "./routes/user.ts": $user,
  },
  islands: {
    "./islands/KvExplorer.tsx": $KvExplorer,
    "./islands/LocalKvList.tsx": $LocalKvList,
    "./islands/RemoteControls.tsx": $RemoteControls,
    "./islands/RemoteKvList.tsx": $RemoteKvList,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
