// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_500 from "./routes/_500.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $api_blob_download_id_path_ from "./routes/api/blob/download/[id]/[...path].ts";
import * as $api_blob_serve_id_path_ from "./routes/api/blob/serve/[id]/[...path].ts";
import * as $api_jobs_id_ from "./routes/api/jobs/[id].ts";
import * as $api_jobs_index from "./routes/api/jobs/index.ts";
import * as $api_kv_id_path_ from "./routes/api/kv/[id]/[...path].ts";
import * as $api_kv_id_bulk_path_ from "./routes/api/kv/[id]/_bulk/[...path].ts";
import * as $api_local_index from "./routes/api/local/index.ts";
import * as $api_remote_check from "./routes/api/remote/check.ts";
import * as $api_remote_index from "./routes/api/remote/index.ts";
import * as $api_watch_index from "./routes/api/watch/index.ts";
import * as $api_watch_server from "./routes/api/watch/server.ts";
import * as $docs_index from "./routes/docs/index.tsx";
import * as $index from "./routes/index.tsx";
import * as $job from "./routes/job.tsx";
import * as $local_id_ from "./routes/local/[id].tsx";
import * as $local_index from "./routes/local/index.tsx";
import * as $login from "./routes/login.tsx";
import * as $logout from "./routes/logout.tsx";
import * as $orgs_id_ from "./routes/orgs/[id].tsx";
import * as $orgs_index from "./routes/orgs/index.tsx";
import * as $projects_name_index from "./routes/projects/[name]/index.tsx";
import * as $projects_name_kv_branch_ from "./routes/projects/[name]/kv/[branch].tsx";
import * as $remote_id_ from "./routes/remote/[id].tsx";
import * as $remote_index from "./routes/remote/index.tsx";
import * as $user from "./routes/user.ts";
import * as $watch from "./routes/watch.tsx";
import * as $KeyTree from "./islands/KeyTree.tsx";
import * as $KvExplorer from "./islands/KvExplorer.tsx";
import * as $LocalControls from "./islands/LocalControls.tsx";
import * as $LocalKvList from "./islands/LocalKvList.tsx";
import * as $RemoteControls from "./islands/RemoteControls.tsx";
import * as $RemoteKvList from "./islands/RemoteKvList.tsx";
import * as $Watches from "./islands/Watches.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_500.tsx": $_500,
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.ts": $_middleware,
    "./routes/api/blob/download/[id]/[...path].ts": $api_blob_download_id_path_,
    "./routes/api/blob/serve/[id]/[...path].ts": $api_blob_serve_id_path_,
    "./routes/api/jobs/[id].ts": $api_jobs_id_,
    "./routes/api/jobs/index.ts": $api_jobs_index,
    "./routes/api/kv/[id]/[...path].ts": $api_kv_id_path_,
    "./routes/api/kv/[id]/_bulk/[...path].ts": $api_kv_id_bulk_path_,
    "./routes/api/local/index.ts": $api_local_index,
    "./routes/api/remote/check.ts": $api_remote_check,
    "./routes/api/remote/index.ts": $api_remote_index,
    "./routes/api/watch/index.ts": $api_watch_index,
    "./routes/api/watch/server.ts": $api_watch_server,
    "./routes/docs/index.tsx": $docs_index,
    "./routes/index.tsx": $index,
    "./routes/job.tsx": $job,
    "./routes/local/[id].tsx": $local_id_,
    "./routes/local/index.tsx": $local_index,
    "./routes/login.tsx": $login,
    "./routes/logout.tsx": $logout,
    "./routes/orgs/[id].tsx": $orgs_id_,
    "./routes/orgs/index.tsx": $orgs_index,
    "./routes/projects/[name]/index.tsx": $projects_name_index,
    "./routes/projects/[name]/kv/[branch].tsx": $projects_name_kv_branch_,
    "./routes/remote/[id].tsx": $remote_id_,
    "./routes/remote/index.tsx": $remote_index,
    "./routes/user.ts": $user,
    "./routes/watch.tsx": $watch,
  },
  islands: {
    "./islands/KeyTree.tsx": $KeyTree,
    "./islands/KvExplorer.tsx": $KvExplorer,
    "./islands/LocalControls.tsx": $LocalControls,
    "./islands/LocalKvList.tsx": $LocalKvList,
    "./islands/RemoteControls.tsx": $RemoteControls,
    "./islands/RemoteKvList.tsx": $RemoteKvList,
    "./islands/Watches.tsx": $Watches,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
