name: ci

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["v1.x", canary]
    steps:
      - name: clone repository
        uses: actions/checkout@v3

      - name: install deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.version }}

      - name: check repo
        run: deno task check

      - name: run tests
        run: deno task test
